name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: [ master, dev, preview ]
    paths:
    - "src/**"
    - "build/**"

env:
  DotNetVersion: 6.0.100
  NugetApiKey: ${{secrets.NUGETAPIKEY}}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - name: Generate Build Number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Build
      run: dotnet run --project build/Build.csproj --BuildNumber=${{steps.buildnumber.outputs.build_number}}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nugets
        path: ${{ github.workspace }}/artifacts
        retention-days: 5
