name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: [ master, dev, preview ]
    paths:
    - "src/**"
    - "build/**"

env:
  #DotNetVersion: 6.0.100
  DotNetVersion: 5.0.403
  NugetApiKey: ${{secrets.NUGETAPIKEY}}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DotNetVersion }}

    - name: Generate Build Number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    #- name: Build
    #  run: dotnet run --project build/Build.csproj --BuildNumber=${{steps.buildnumber.outputs.build_number}}

    #- name: Publish Artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: nugets
    #    path: ${{ github.workspace }}/artifacts
    #    retention-days: 5

    - name: Build
      run: dotnet msbuild Build.slnf /p:LibraryVersion=${env.Version}.${{steps.buildnumber.outputs.build_number}}

    - name: Publish to Nuget
      if: ${{ github.ref == 'refs/heads/master' }}
      run: dotnet nuget push **/*.nupkg --api-key ${{ env.NugetApiKey }}

    #- name: Create Release
    #  id: create_release
    #  if: ${{ github.ref == 'refs/heads/master' }}
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #  with:
    #    tag_name: ${{ github.ref }}
    #    release_name: Release ${{ github.ref }}
    #    body: Release
    #    draft: false
    #    prerelease: false